### ISSUE TITLE
[FR] Exponential Drive Capabilities

### ISSUE THREAD

**Issue by pixelated-pup** [ProjectBucephalus/Energize#16]
### Name

Alec

### Feature Description

Manage joystick capabilities exponentially

### Feature Timeline

It has previously existed on previous robots and is standard for fast drivetrains

### Expected behavior

Moving the joystick doesn't output it's values linearly to motor controls, but rather exponentially (so that sensitivity is decreased)

### Justification

Tipping is bad

### Possible implications

Driver's might not want

### Implimentation

Math.pow(joystick.getY(), 2)

### Importance

High (eg. part of the robot is not quite working properly)

**Comment by LordBBQ** [comment]
We need to do further testing with this code before committing to using exponential drive, some of the drivers are concerned. This will likely come down to driver preference once a driver is selected. 

Also, in future please don’t put the approved label on yourself, or move it to the approved as we have a process for making sure multiple people are involved in these decisions. :)

**Comment by pixelated-pup** [comment]
Adam was the one who approved it. Also as far as I know, we have already committed to using exponential drive. You might want to check with Graham.

**Comment by LordBBQ** [comment]
Ok cool, I saw your account added the tags. Nice work on all that.

**Comment by pixelated-pup** [comment]
Implemented with constants so that it is configurable
