### ISSUE TITLE
[BUG] Joystick Axes Inverted

### ISSUE THREAD

**Issue by pixelated-pup** [ProjectBucephalus/Energize#17]
### Name

Alec

### Bug Description

Joystick axes inverted, all motors set to run Clockwise. Two wrongs made a right, but any changes to exponentials on the axes were applied to the wrong axis

### Bug Timeline

First noticed today (19/02)

### Expected behavior

Expected it to apply the exponential on the Y axis to power, applied to rotation instead.

### Steps to Reproduce

Apply exponential to one axis, test what direction of movement it actually gets applied to 

### Version of software

19/02/2023, pre-4 o'clock

### Dashboard

None

### Importance

High (eg. part of the robot is not quite working properly)

**Comment by gcgcgcgc** [comment]
Issue verified from first principles comparing joystick axes in driver station to code, and comparing wheel rotations against motors (motors double checked in Phoenix Tuner).

Joystick axes are swapped. Motor rotation directions are inconsistent. Bug is confirmed.

**Comment by pixelated-pup** [comment]
Tested, working, now closing (fixed code committed to bringup)
