### ISSUE TITLE
Bug report by liz: critical

### ISSUE THREAD

**Issue by team5985** [ProjectBucephalus/Energize#20]
**Name:** liz

**Severity:**  critical

**Current Version:** n/a 

**Description:**
programming team needs to fill out mentor form

**Timeline:**
last month

**Expected behavior:**
all team members to fill at least 2 in

**Actual behavior:**
has not been completed 

**Steps to reproduce:**
1. click the link in the chat
2. select mentor
3. write message
4. submit
5, repeatn
**Additional Information:**
n/a

 **User:** {'id': 'UME3CTMCJ', 'username': 'elizabeth.crowe4', 'name': 'elizabeth.crowe4', 'team_id': 'THX5M8PFC'}

**Comment by LordBBQ** [comment]
Please update the issue description with an in-depth description of the issue, including robot code version, and robot details.

**Comment by sillylittlerobots** [comment]
Issue not related/not enough info
