### ISSUE TITLE
Bug report by Test: D

### ISSUE THREAD

**Issue by team5985** [ProjectBucephalus/Energize#4]
**Name:** Test

**Severity:**  D

**Current Version:** F 

**Description:**
F

**Timeline:**
X

**Expected behavior:**
A

**Actual behavior:**
G

**Steps to reproduce:**
Dn
**Additional Information:**
H

 **User:** {'id': 'UMHQWCM2M', 'username': 'joshua.d.moran', 'name': 'joshua.d.moran', 'team_id': 'THX5M8PFC'}

**Comment by LordBBQ** [comment]
Help

**Comment by LordBBQ** [comment]
Help me please test

**Comment by team5985** [comment]
There is no help
